### ISSUE TITLE
Set KOTLIN_HOME

### ISSUE THREAD

**Issue by jayvdb** [fwilhe2/setup-kotlin#430]
It would be helpful if this action also set `KOTLIN_HOME` to the appropriate path.

I've run into several cases where tools require it to be set, or require a cli arg provided with this value.  c.f. https://github.com/scijava/jgo/issues/89

**Comment by fwilhe2** [comment]
Hi @jayvdb 

thanks for the suggestion. So far I've never encountered `KOTLIN_HOME` (sounds a lot like `JAVA_HOME`).

I'd be happy to have the action do this, but I'm not sure when I'll be doing it. Would you be able to provide a PR for the feature, or a failing test to verify it works when implemented?

Just out of curiosity, can you tell me what you're using this action for? Since [kotlin is preinstalled on GitHub's runners now](https://github.com/actions/runner-images/issues/3687), the use-cases for this action became quite narrow and I don't really use it myself, so I'm not putting that much effort into maintenance as also I don't know of many "productive" users.

Happy new year (in :australia: at least :sweat_smile:)

**Comment by fwilhe2** [comment]
I think this is fixed by https://github.com/fwilhe2/setup-kotlin/pull/451
